version: '3'
services:
    web:
        build:
            context: ./web
            dockerfile: Dockerfile
        ports:
            - "80:80"
    xss:
        build:
            context: ./xss
            dockerfile: Dockerfile
        ports:
            - "5000:22"
    db:
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - "3306:3306"